#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'self-driving-car-pkg','console_scripts','drive_node'
__requires__ = 'self-driving-car-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('self-driving-car-pkg', 'console_scripts', 'drive_node')()
    )
